"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class jumping_robot_trunk_state_t(object):
    __slots__ = ["timestamp", "finished", "base_p", "base_pd", "base_pdd", "base_rpy", "base_rpyd", "base_rpydd", "lfoot_p", "rfoot_p", "lfoot_pd", "rfoot_pd", "lfoot_pdd", "rfoot_pdd", "lfoot_contact", "rfoot_contact", "lfoot_f", "rfoot_f"]

    __typenames__ = ["double", "boolean", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "boolean", "boolean", "double", "double"]

    __dimensions__ = [None, None, [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], None, None, [6], [6]]

    def __init__(self):
        self.timestamp = 0.0
        self.finished = False
        self.base_p = [ 0.0 for dim0 in range(3) ]
        self.base_pd = [ 0.0 for dim0 in range(3) ]
        self.base_pdd = [ 0.0 for dim0 in range(3) ]
        self.base_rpy = [ 0.0 for dim0 in range(3) ]
        self.base_rpyd = [ 0.0 for dim0 in range(3) ]
        self.base_rpydd = [ 0.0 for dim0 in range(3) ]
        self.lfoot_p = [ 0.0 for dim0 in range(3) ]
        self.rfoot_p = [ 0.0 for dim0 in range(3) ]
        self.lfoot_pd = [ 0.0 for dim0 in range(3) ]
        self.rfoot_pd = [ 0.0 for dim0 in range(3) ]
        self.lfoot_pdd = [ 0.0 for dim0 in range(3) ]
        self.rfoot_pdd = [ 0.0 for dim0 in range(3) ]
        self.lfoot_contact = False
        self.rfoot_contact = False
        self.lfoot_f = [ 0.0 for dim0 in range(6) ]
        self.rfoot_f = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(jumping_robot_trunk_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">db", self.timestamp, self.finished))
        buf.write(struct.pack('>3d', *self.base_p[:3]))
        buf.write(struct.pack('>3d', *self.base_pd[:3]))
        buf.write(struct.pack('>3d', *self.base_pdd[:3]))
        buf.write(struct.pack('>3d', *self.base_rpy[:3]))
        buf.write(struct.pack('>3d', *self.base_rpyd[:3]))
        buf.write(struct.pack('>3d', *self.base_rpydd[:3]))
        buf.write(struct.pack('>3d', *self.lfoot_p[:3]))
        buf.write(struct.pack('>3d', *self.rfoot_p[:3]))
        buf.write(struct.pack('>3d', *self.lfoot_pd[:3]))
        buf.write(struct.pack('>3d', *self.rfoot_pd[:3]))
        buf.write(struct.pack('>3d', *self.lfoot_pdd[:3]))
        buf.write(struct.pack('>3d', *self.rfoot_pdd[:3]))
        buf.write(struct.pack(">bb", self.lfoot_contact, self.rfoot_contact))
        buf.write(struct.pack('>6d', *self.lfoot_f[:6]))
        buf.write(struct.pack('>6d', *self.rfoot_f[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != jumping_robot_trunk_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return jumping_robot_trunk_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = jumping_robot_trunk_state_t()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.finished = bool(struct.unpack('b', buf.read(1))[0])
        self.base_p = struct.unpack('>3d', buf.read(24))
        self.base_pd = struct.unpack('>3d', buf.read(24))
        self.base_pdd = struct.unpack('>3d', buf.read(24))
        self.base_rpy = struct.unpack('>3d', buf.read(24))
        self.base_rpyd = struct.unpack('>3d', buf.read(24))
        self.base_rpydd = struct.unpack('>3d', buf.read(24))
        self.lfoot_p = struct.unpack('>3d', buf.read(24))
        self.rfoot_p = struct.unpack('>3d', buf.read(24))
        self.lfoot_pd = struct.unpack('>3d', buf.read(24))
        self.rfoot_pd = struct.unpack('>3d', buf.read(24))
        self.lfoot_pdd = struct.unpack('>3d', buf.read(24))
        self.rfoot_pdd = struct.unpack('>3d', buf.read(24))
        self.lfoot_contact = bool(struct.unpack('b', buf.read(1))[0])
        self.rfoot_contact = bool(struct.unpack('b', buf.read(1))[0])
        self.lfoot_f = struct.unpack('>6d', buf.read(48))
        self.rfoot_f = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if jumping_robot_trunk_state_t in parents: return 0
        tmphash = (0x3115b03c2e850905) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if jumping_robot_trunk_state_t._packed_fingerprint is None:
            jumping_robot_trunk_state_t._packed_fingerprint = struct.pack(">Q", jumping_robot_trunk_state_t._get_hash_recursive([]))
        return jumping_robot_trunk_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", jumping_robot_trunk_state_t._get_packed_fingerprint())[0]

